app = 'microservicea'
primary_region = 'sea'

[build]

[[services]]
  internal_port = 5555
  protocol = "tcp"
  force_https = true
  min_machines_running = 1
  auto_stop_machines = false
  auto_start_machines = true
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
